monitor.alsa.rules = [
  {
    matches = [{ node.name = "~alsa_output.*analog.*" }]
    actions = {
      update-props = {
        api.alsa.period-size   = 1024
        api.alsa.headroom      = 0
        node.latency           = "1024/48000"
      }
    }
  }
]
