hl.bind(MAIN_MOD .. " + RETURN", hl.dsp.exec_cmd(TERMINAL))
hl.bind(MAIN_MOD .. " + Q", hl.dsp.window.close())
hl.bind(MAIN_MOD .. " + E", hl.dsp.exec_cmd(FILE_MANAGER))
hl.bind(MAIN_MOD .. " + SHIFT + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(MAIN_MOD .. " + D", hl.dsp.exec_cmd(MENU))
hl.bind(MAIN_MOD .. " + SHIFT + P", hl.dsp.window.pseudo())
hl.bind(MAIN_MOD .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(MAIN_MOD .. " + F", hl.dsp.window.fullscreen())
hl.bind(MAIN_MOD .. " + c", hl.dsp.exec_cmd("vicinae vicinae://extensions/vicinae/clipboard/history"))
hl.bind(MAIN_MOD .. " + O", hl.dsp.exec_cmd("ghostty -e $HOME/.opencode/bin/opencode"))
hl.bind(MAIN_MOD .. " + SHIFT + O", hl.dsp.exec_cmd("~/.config/hypr/opencode-toggle.sh"))

hl.bind(MAIN_MOD .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(MAIN_MOD .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(MAIN_MOD .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(MAIN_MOD .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(MAIN_MOD .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(MAIN_MOD .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(MAIN_MOD .. " + SHIFT + up", hl.dsp.window.move({ direction = "up" }))
hl.bind(MAIN_MOD .. " + SHIFT + down", hl.dsp.window.move({ direction = "down" }))

hl.bind(MAIN_MOD .. " + t", hl.dsp.group.toggle())
hl.bind(MAIN_MOD .. " + SHIFT + T", hl.dsp.window.move({ out_of_group = true }), { description = "Move active window out of group" })
hl.bind("ALT + left", hl.dsp.group.prev())
hl.bind("ALT + right", hl.dsp.group.next())

hl.bind(MAIN_MOD .. " + 1", hl.dsp.focus({ workspace = "1" }))
hl.bind(MAIN_MOD .. " + 2", hl.dsp.focus({ workspace = "2" }))
hl.bind(MAIN_MOD .. " + 3", hl.dsp.focus({ workspace = "3" }))
hl.bind(MAIN_MOD .. " + 4", hl.dsp.focus({ workspace = "4" }))
hl.bind(MAIN_MOD .. " + 5", hl.dsp.focus({ workspace = "5" }))
hl.bind(MAIN_MOD .. " + 6", hl.dsp.focus({ workspace = "6" }))
hl.bind(MAIN_MOD .. " + 7", hl.dsp.focus({ workspace = "7" }))
hl.bind(MAIN_MOD .. " + 8", hl.dsp.focus({ workspace = "8" }))
hl.bind(MAIN_MOD .. " + 9", hl.dsp.focus({ workspace = "9" }))
hl.bind(MAIN_MOD .. " + 0", hl.dsp.focus({ workspace = "10" }))
hl.bind(MAIN_MOD .. " + ALT + 1", hl.dsp.focus({ workspace = "11" }))
hl.bind(MAIN_MOD .. " + ALT + 2", hl.dsp.focus({ workspace = "12" }))

hl.bind(MAIN_MOD .. " + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }))
hl.bind(MAIN_MOD .. " + SHIFT + 2", hl.dsp.window.move({ workspace = "2" }))
hl.bind(MAIN_MOD .. " + SHIFT + 3", hl.dsp.window.move({ workspace = "3" }))
hl.bind(MAIN_MOD .. " + SHIFT + 4", hl.dsp.window.move({ workspace = "4" }))
hl.bind(MAIN_MOD .. " + SHIFT + 5", hl.dsp.window.move({ workspace = "5" }))
hl.bind(MAIN_MOD .. " + SHIFT + 6", hl.dsp.window.move({ workspace = "6" }))
hl.bind(MAIN_MOD .. " + SHIFT + 7", hl.dsp.window.move({ workspace = "7" }))
hl.bind(MAIN_MOD .. " + SHIFT + 8", hl.dsp.window.move({ workspace = "8" }))
hl.bind(MAIN_MOD .. " + SHIFT + 9", hl.dsp.window.move({ workspace = "9" }))
hl.bind(MAIN_MOD .. " + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }))

hl.bind(MAIN_MOD .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(MAIN_MOD .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(MAIN_MOD .. " + SHIFT + Page_Down", hl.dsp.exec_cmd("grimblast --freeze copysave active ~/Pictures/Screenshots/$(date +'%y%m%d_%Hh%Mm%Ss')_window.png"))
hl.bind(MAIN_MOD .. " + SHIFT + Page_Up", hl.dsp.exec_cmd("grim -g \"$(slurp -o -r -c '##ff0000ff')\" -t ppm - | satty --filename - --output-filename ~/Pictures/Screenshots/satty-$(date '+%Y%m%d-%H:%M:%S').png"))
hl.bind(MAIN_MOD .. " + SHIFT + S", hl.dsp.exec_cmd("grimblast --freeze copysave area ~/Pictures/Screenshots/$(date +'%y%m%d_%Hh%Mm%Ss')_region.png"))
hl.bind(MAIN_MOD .. " + SHIFT + D", hl.dsp.exec_cmd("TEMP=/tmp/satty-$(date +%s).png && grimblast --freeze copysave area ~/Pictures/Screenshots/$(date +'%y%m%d_%Hh%Mm%Ss')_screenshot.png && wl-paste > $TEMP && satty --filename $TEMP --copy-command wl-copy && rm $TEMP"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"), { locked = true })

hl.bind(MAIN_MOD .. " + mouse_down", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 + 0.5}')"))
hl.bind(MAIN_MOD .. " + mouse_up", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 - 0.5}')"))
hl.bind(MAIN_MOD .. " + SHIFT + mouse_up", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1"))

hl.bind(MAIN_MOD .. " + period", hl.dsp.exec_cmd("vicinae vicinae://extensions/vicinae/vicinae/search-emojis"))

hl.bind("CTRL + 0", hl.dsp.pass({ window = "class:^(com.obsproject.Studio)$" }))
