hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("~/.config/hypr/xdg.sh")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("xwaylandvideobridge")
    hl.exec_cmd("waybar & swaync")
    hl.exec_cmd("easyeffects --gapplication-service")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("vicinae server")
    hl.exec_cmd("command -v Telegram >/dev/null 2>&1 && hyprctl dispatch exec \"[workspace 13 silent] Telegram\"")
    hl.exec_cmd("command -v throne >/dev/null 2>&1 && hyprctl dispatch exec \"[workspace 8 silent] throne\"")
    hl.exec_cmd("command -v polychromatic-tray-applet >/dev/null 2>&1 && polychromatic-tray-applet")
    hl.exec_cmd("command -v ags >/dev/null 2>&1 && ags")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme \"prefer-dark\"")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme \"adw-gtk3-dark\"")
    hl.exec_cmd("gsettings set org.cinnamon.desktop.default-applications.terminal exec " .. TERMINAL)
end)
